//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 10:01:09 AM on Friday, November 14, 2008
//
//	Generated for file: nsbasic.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"NSBRuntime"
//
//	Palm App Version:		"6.1.1 ARM"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutStarterApp                1000


//	Resource: tSTR 1234
#define k1234testString                           1234	// "yufDwgTBsCWMbFyApYKHexPKRlqkDgnZreSpdUMmXIWMzIGCBuRgWyNFLjjfDuRZ"


//	Resource: PICT 1000
#define BitmapID1000Bitmap                        1000


//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000

