//	Header generated by Constructor for Pilot 1.0.2
//
//	Generated at 1:36:48 AM on Saturday, April 17, 1999
//
//	Generated for file: D:\StylusBasicTemplate\template\Src\Starter.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Pilot App Name: 		"Starter"
//
//	Pilot App Version: 		"1.0"


